version: "3.8"

services:
    # Service Laravel dengan PHP-FPM
    laravel:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        command: php-fpm
        expose:
            - "9000"
        networks:
            - laravel-network

    # Service Nginx untuk menangani request HTTP
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_app
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
